#!/bin/bash

function die() {
    echo $@
    exit 1   
}

# Check usage
app_home="$1"
test -z $app_home || die "usage: $0 TARGET_DIRECTORY [VERSION]"

app=$(basename $app_home)

# Initialize, get current date, if deploying around 00:00
date_cur=$(date '+%Y-%m-%d')

# Allow user to override what date to rollback from
if [ "$2" ]; then
  date_cur="$2"
fi

test ! -f $app_home || die "No application installed in $app_home"
test ! -f /var/backups/${app}/${app}_${date_cur}.tar.bz2  || die "No backup of $app exists from $date_cur"

#
# Do reverse migrations
#
...

# Drop any existing version. Depending on when the deploy command failed,
# this command may fail. This is not a bug.
rm -rf $app_home

# Move to root since the archives are created with absolute paths
cd /

# Do the actual rollback
tar jxpf /var/backups/${app}/${app}_${date_cur}.tar.bz2 || die "Unable to restore from backup"

echo "Backup restored. Be more careful next time!"
